---
bind: 127.0.0.1
port: 8125

# Flush interval should be your finest retention in seconds
flush_interval: 10
cleanup_interval: 30

# Redis
redis_host: localhost 
redis_port: 6379
# Uses the same format as graphite's schema retentions, accomplished by
# storing aggregated keys at each retention level. 
# "10:2160,60:10080,600:262974" translates to:
# 6 hours of 10 second data (what we consider "near-realtime")
# 1 week of 1 minute data
# 5 years of 10 minute data
retention: "10:2160,60:10080,600:262974"
coalmine_data_path: "/u/statsd/"

